version: '3'

services:
  mysql:
    image: mysql:latest
    restart: always
    expose:
      - "3306"
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: mysqlpwd
    volumes:
      - /etc/locatime:/etc/locatime:ro
      - ./var/lib/mysql:/var/lib/mysql
      - ./mysql/create_db.sql:/docker-entrypoint-initdb.d/create_db.sql:ro
      - ./mysql/custom.cnf:/etc/mysql/conf.d/custom.cnf:ro
    networks:
      - kaoyan

  app:
    image: dashmrl/kaoyan:latest
    build:
      context: .
      dockerfile: DockerfileOnline
    restart: always
    ports:
      - "3003:8080"
    environment:
      TZ: Asia/Shanghai
    volumes:
      - /etc/locatime:/etc/locatime:ro
    depends_on:
      - mysql
    networks:
      - kaoyan
networks:
  kaoyan: