version: '3'

services:
  mysql:
    image: mysql:latest
    restart: always
    expose:
      - "3306"
    volumes:
      - ./mysql/create_db.sql:/docker-entrypoint-initdb.d/create_db.sql:ro
      - ./mysql/custom.cnf:/etc/mysql/conf.d/custom.cnf:ro
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: mysqlpwd
    networks:
      - kaoyan
  app:
    image: dashmrl/kaoyan
    restart: always
    ports:
      - "3003:8080"
      - "5005:5005"
    environment:
      TZ: Asia/Shanghai
      JAVA_OPTS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005,quiet=y
    depends_on:
      - mysql
    networks:
      - kaoyan

networks:
  kaoyan: