#spring:
#  profiles:
#    active: prod

debug: true

spring:
  jpa:
    database: MYSQL
    show-sql: true
    hibernate.ddl-auto: update
    hibernate.naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    username: root
    password: mysqlpwd
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/kaoyan?characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    druid:
          connection-init-sqls: ["SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci"]
    max-active: 20
    max-idle: 8
    min-idle: 8
    initial-size: 10
#  jwt:
#    header: Authorization
#    tokenHead: "Bearer "
#    secret: mySecret
#    expiration: 259200
  admin:
    uname: admin
    pwd: letsgodude
    phone: 15200296920